# /*---------------------------------------------------------------------------8
# |                                                                            |
# |     This workflows Downloads the SAP Software with GitHub Actions          |
# |                                                                            |
# +------------------------------------4--------------------------------------*/

name:                                             065 - Download SAP software - new

run-name:                                         Download SAP software @${{ github.actor }}

on:
  workflow_dispatch:
    inputs:
      application_bom_base_name:
        description:                              "Name of Application Bill of Materials (BoM)"
        required:                                 true
        type:                                     choice
        options:
          - APP_S4_2025_v0001ms
          - APP_S4_2023_v0001ms
          - APP_S4_2022_v0001ms
          - APP_NW_750_v0001ms
          - APP_NW_750_JAVA_v0001ms

      kernel_bom_base_name:
        description:                              "Name of Kernel Bill of Materials (BoM)"
        required:                                 true
        type:                                     choice
        options:
          - SAP_KERNEL_916_latest
          - SAP_KERNEL_793_latest
          - SAP_KERNEL_754_latest
          - SAP_KERNEL_753_latest

      db_bom_base_name:
        description:                              "Name of Database Bill of Materials (BoM)"
        required:                                 true
        type:                                     choice
        options:
          - DB_HANA_2_00_SPS06_latest
          - DB_HANA_2_00_SPS07_latest
          - DB_HANA_2_00_SPS08_latest
          - DB_Oracle19_v2602ms
          - DB_Oracle19_v2511ms
          - DB_Oracle19_v2508ms
          - DB2_UDB_11_5_v0001ms
          - DB_MSSQLSRV_2019_v0001ms
          - DB_SYBASE_1603SP15_v0003ms

      platform:
        description:                              "Name of Platform"
        required:                                 true
        type:                                     choice
        options:
          - HANA
          - ORACLE
          - ORACLE-ASM
          - DB2
          - SQLSERVER
          - SYBASE

      bom_save_name:
          description:                            "Name for the combined BoM, defaults to Application BoM name"
          type:                                   string
          default:                                ""

      bom_override_name:
          description:                            "Custom Bill of Materials. Use format (App BoM-Db BoM-Kernel Bom-CustomName), for example AppBom-DBBoM-S4BoM"
          type:                                   string
          default:                                ""

      control_plane_name:
        description:                              "Control Plane Environment"
        required:                                 true
        type:                                     environment

      re_download:
        description:                              "Re-download"
        type:                                     boolean
        default:                                  false

      extra_params:
          description:                            "Extra Parameters"
          type:                                   string
          default:                                ""

permissions:
  contents:                                       write
  id-token:                                       write
  issues:                                         write

env:
  TF_IN_AUTOMATION:                               ${{ vars.TF_IN_AUTOMATION }}
  TF_LOG:                                         ${{ vars.TF_LOG }}
  ANSIBLE_CORE_VERSION:                           ${{ vars.ANSIBLE_CORE_VERSION }}
  TF_VERSION:                                     ${{ vars.TF_VERSION }}
  SAMPLE_REPO_PATH:                               ${{ github.workspace }}/SAP-automation-samples

jobs:
  prepare_download:
    name:                                         Download Software
    environment:                                  ${{ inputs.control_plane_name }}
    runs-on:                                      self-hosted
    container:
      image:                                      ${{ vars.DOCKER_IMAGE }}

    steps:
      - name:                                     Get app token
        id:                                       get_workflow_token
        uses:                                     actions/create-github-app-token@v3
        with:
          client-id:                              ${{ secrets.APPLICATION_ID }}
          private-key:                            ${{ secrets.APPLICATION_PRIVATE_KEY }}

      - name:                                     Configure Git Safe Directory
        run:                                      |
          git config --global --add safe.directory "$GITHUB_WORKSPACE"
          git config --global --add safe.directory "/__w/${{ github.event.repository.name }}/${{ github.event.repository.name }}"

      - name:                                     Checkout Config Repository
        uses:                                     actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          fetch-depth:                            0

      - name:                                     Checkout Samples Repository
        uses:                                     actions/checkout@v6
        with:
          repository:                             Azure/SAP-automation-samples
          path:                                   SAP-automation-samples

      - name:                                     Azure Login with User Managed Identity
        if:                                       ${{ vars.USE_MSI == 'true' }}
        uses:                                     azure/login@v3
        with:
          auth-type:                              IDENTITY
          client-id:                              ${{ vars.ARM_CLIENT_ID }}
          tenant-id:                              ${{ vars.ARM_TENANT_ID }}
          subscription-id:                        ${{ vars.ARM_SUBSCRIPTION_ID }}
          enable-AzPSSession:                     false

      - name:                                     Azure Login with Service Principal
        if:                                       ${{ vars.USE_MSI != 'true' }}
        uses:                                     azure/login@v3
        with:
          creds:                                  |
           {
                                                  "clientId": "${{ vars.ARM_CLIENT_ID }}",
                                                  "clientSecret": "${{ secrets.ARM_CLIENT_SECRET }}",
                                                  "subscriptionId": "${{ vars.ARM_SUBSCRIPTION_ID }}",
                                                  "tenantId": "${{ vars.ARM_TENANT_ID }}"
           }

      - name:                                     Prepare SAP software download
        run:                                      |
          cd ${SAP_AUTOMATION_REPO_PATH}
          chmod +x deploy/scripts/pipeline_scripts/04-sap-software-download-prepare.sh
          deploy/scripts/pipeline_scripts/04-sap-software-download-prepare.sh
        env:
          APPLICATION_CONFIGURATION_NAME:         ${{ vars.APPLICATION_CONFIGURATION_NAME }}
          APP_TOKEN:                              ${{ steps.get_workflow_token.outputs.token }}
          BOM:                                    ${{ inputs.bom_override_name != '' && inputs.bom_override_name || format('{0}-{1}-{2}-{3}', inputs.application_bom_base_name, inputs.db_bom_base_name, inputs.kernel_bom_base_name, inputs.bom_save_name) }}
          CONTROL_PLANE_NAME:                     ${{ inputs.control_plane_name }}
          DEPLOYER_KEYVAULT:                      ${{ vars.DEPLOYER_KEYVAULT }}
          re_download:                            ${{ inputs.re_download }}
          ARM_CLIENT_ID:                          ${{ vars.ARM_CLIENT_ID }}
          ARM_CLIENT_SECRET:                      ${{ secrets.ARM_CLIENT_SECRET }}
          ARM_SUBSCRIPTION_ID:                    ${{ vars.ARM_SUBSCRIPTION_ID }}
          ARM_TENANT_ID:                          ${{ vars.ARM_TENANT_ID }}
          SUSERNAME:                              ${{ vars.S_USERNAME }}
          SPASSWORD:                              ${{ secrets.S_PASSWORD }}
          USE_MSI:                                ${{ vars.USE_MSI }}
          TF_VAR_use_spn:                         ${{ vars.USE_MSI }}
          tf_version:                             ${{ env.TF_VERSION }}
          EXTRA_PARAMETERS:                       ${{  format('-e platform={0} {1}', inputs.platform, inputs.extra_params) }}
